global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'account_update_exporter'
    static_configs:
      - targets: [ 'event_processor:9100' ]

remote_write:
  - url: remote_write_url
    basic_auth:
      username: remote_write_username
      password: remote_write_password
